Create a service for products
ProjektKuro/kuro-web pull request #50
Opened 2020-04-05 20:22 UTC by SvenPatrickMeier

Adds a Service and corresponding `vuex` Store for Products. Closes #15

2020-04-05 20:25 UTC, SvenPatrickMeier commented
WIP will be resolved when #51 can be closed.

2020-04-06 00:57 UTC, SvenPatrickMeier commented
commit 2f6a402 fixes #51

2020-04-06 10:41 UTC, tlahmann requested changes

2020-04-06 10:41 UTC, tlahmann commented on src/services/api/productService.ts
> +        return await BaseApiService.instance.read("/products");
Either embed this line in a try catch block or split this line into two. [ES-lint rule](https://github.com/eslint/eslint/blob/master/docs/rules/no-return-await.md) & [another example](https://jakearchibald.com/2017/await-vs-return-vs-return-await/#return-awaiting).

The same applies to all return await calls.

2020-04-06 10:41 UTC, tlahmann commented on src/services/api/base.ts
> +    return await this.http.get(resource);
Either embed this line in a try catch block or split this line into two. [ES-lint rule](https://github.com/eslint/eslint/blob/master/docs/rules/no-return-await.md) & [another example](https://jakearchibald.com/2017/await-vs-return-vs-return-await/#return-awaiting).

The same applies to all return await calls.

2020-04-07 23:02 UTC, tlahmann commented
@SvenPatrickMeier, Is this ready to merge?

2020-04-07 23:06 UTC, SvenPatrickMeier commented
@tlahmann Almost ready. Will finish tomorrow!

2020-04-10 16:59 UTC, SvenPatrickMeier commented
Ready to merge after review.

2020-04-13 22:17 UTC, tlahmann approved these changes

2020-04-13 22:32 UTC, merged